# Bot Configuration Settings

BOT_TOKEN = '7637715655:AAHJUlqtUjUVC67xZqsVxNRh2cmkGJZVmms'
LOG_LEVEL = 'info'
LOG_FILE = 'bot.log'
BOT_NAME = 'YourBotName'
BOT_VERSION = '1.0.0'

# Optional API Keys
WEATHER_API_KEY = 'YOUR_WEATHER_API_KEY_HERE'
NEWS_API_KEY = 'YOUR_NEWS_API_KEY_HERE'
